# Generated by Django 3.1.6 on 2021-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
