# Generated by Django 3.1.6 on 2021-03-21 11:40

from django.db import migrations, models
import notes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210321_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='notes/', validators=[notes.validators.validate_file_size]),
        ),
    ]
